public enum CombatPhase
{
    INIT,
    WAVE_SETUP,
    CHARACTERTURN_PREFLIGHT,
    CHARACTERTURN_CHOOSEABILITY,
    CHARACTERTURN_CHOOSETARGET,
    CHARACTERTURN_EXECUTION,
    CHARACTERTURN_CLEANUP,
    CHARACTERTURN_HANDOFF,
    WAVE_COMPLETE
}
