public enum UserAbilitySelection {
    NONE,
    BASICATTACK,
    SHIELDBASH,
    SNEAKATTACK,
    CURSEOFSTRENGTH,
    BLESSING,
    DEADLYPOUNCE,
    CELESTIALBARRAGE,
    POLYMORPH,
    MASSHEAL
}
